In [3]:
import numpy as np



In [8]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

type(my_list)


list

In [11]:
arr = np.array(my_list)

In [13]:
type(arr)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


In [19]:
print(np.zeros(3))

[0. 0. 0.]


In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [24]:
np.random.rand(2)

array([0.94397869, 0.62220143])

In [25]:
np.random.rand(5,5)

array([[0.72146248, 0.58099226, 0.23950597, 0.76482247, 0.41469728],
       [0.33055657, 0.32549986, 0.69760414, 0.22926047, 0.72519451],
       [0.52724009, 0.61065915, 0.53069075, 0.66313687, 0.25591419],
       [0.76704429, 0.05861824, 0.38001244, 0.74008059, 0.99074157],
       [0.58561037, 0.85337511, 0.67703888, 0.54560015, 0.12149212]])

In [28]:
np.random.randn(2)

array([-0.57553249, -1.32743856])

In [29]:
np.random.randint(1,100,10)

array([36, 30, 71, 39, 24, 46, 14, 46, 16, 10])

In [30]:
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [34]:
np.random.seed(75)
print(np.random.rand(4))

[0.56894022 0.06596423 0.88811067 0.92965818]


In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[34 17 32  7  6 43 25 45 38 42]


In [38]:
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [39]:
print(ranarr.max())

45


In [40]:
ranarr.argmax()

7

In [41]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [42]:
print(arr[8])

8


In [43]:
print(arr[1:5])

[1 2 3 4]


In [44]:
print(arr[0:5])

[0 1 2 3 4]


In [49]:
arr[0:5] = 123
arr

array([123, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [50]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [51]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]
print(slice_of_arr)

[99 99 99 99 99 99]


In [67]:
slice = arr[1:4]
slice
type(slice)

numpy.ndarray

In [68]:
# slice_of_arr[:]=99
# slice_of_arr
# arr

In [69]:
# slice[:] = 111
# slice
# arr

In [75]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()
arr_copy[1:4] = 90
arr_copy

array([ 0, 90, 90, 90,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [77]:
print(arr>4)

[False False False False False  True  True  True  True  True  True]


In [78]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
bool_arr = arr> 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [80]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr/arr

C:\Users\dai.STUDENTSDC\AppData\Local\Temp\ipykernel_16856\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [82]:
1/arr

C:\Users\dai.STUDENTSDC\AppData\Local\Temp\ipykernel_16856\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [83]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [88]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [90]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [92]:
np.log(arr)

C:\Users\dai.STUDENTSDC\AppData\Local\Temp\ipykernel_16856\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [93]:
arr.sum()

55

In [94]:
arr.mean()

5.0

In [95]:
arr.max()

10

In [96]:
arr.min()

0

In [97]:
arr.var()

10.0

In [98]:
arr.std()

3.1622776601683795

In [99]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
arr_2d.shape

(3, 4)

In [101]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [102]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [114]:
sid = np.arange(1,10)
sidd = np.array(sid)
sidd.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
sidd.sum(axis=0)

45

In [117]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones = np.