In [1]:
import pandas as pd
import numpy as np

In [2]:
ds= pd.Series([1,2,3,4,5])
ds

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
lst = ds.to_list()
lst

[1, 2, 3, 4, 5]

In [4]:
a = pd.Series([2, 4, 6, 8, 10])
b  = pd.Series([1, 3, 5, 7, 9])
a.add(b)

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [5]:
a = pd.Series([2, 4, 6, 8, 10])
b  = pd.Series([1, 3, 5, 7, 9])
a.sub(b)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [6]:
a = pd.Series([2, 4, 6, 8, 10])
b  = pd.Series([1, 3, 5, 7, 9])
a.mul(b)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [7]:
a = pd.Series([2, 4, 6, 8, 10])
b  = pd.Series([1, 3, 5, 7, 9])
a.div(b)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [8]:
a1=  pd.Series([2, 4, 6, 8, 10])
a2= pd.Series([1, 3, 5, 7, 10])
a1==a2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [9]:
d= {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
df = pd.Series(d)
df


a    100
b    200
c    300
d    400
e    800
dtype: int64

In [10]:
arr  = np.array([10, 20, 30, 40, 50])
ds = pd.Series(arr)
ds

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [11]:
ds = pd.Series([100, 200, "python", 300.12, 400])
ds = pd.to_numeric(ds, errors = 'coerce')
ds

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [12]:
data= {'col1' : [1,2,3,4,7,11], 'col2' : [4,5,6,9,5,0], 'col3' : [7,5,8,12,1,11]}
df= pd.DataFrame(data)
pd.Series(df['col1'])


0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

In [13]:
ds = pd.Series([100, 200, "python", 300.12, 400])
a= ds.values
a

array([100, 200, 'python', 300.12, 400], dtype=object)

In [14]:
data= pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
ds= data.apply(pd.Series).stack().reset_index(drop=True)
ds

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [15]:
ds = pd.Series(['100', '200', 'python', '300.12', '400'])
new_ds=pd.Series(ds).sort_values()
new_ds


0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [16]:
ds = pd.Series(['100', '200', 'python', '300.12', '400'])
new_ds= pd.concat([ds,pd.Series([500, "php"])], ignore_index=True)
new_ds

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

In [17]:
ds= pd.Series([0,1,2,3,4,5,6,7,8,9,10])
new_ds= ds[ds<6]
new_ds

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [18]:
ds = pd.Series(data = [1,2,3,4,5], index= ['A','B','C','D','E'])
new_ds = ds.reindex(index= ['B', 'A','C','D','E'])
new_ds

B    2
A    1
C    3
D    4
E    5
dtype: int64

In [19]:
ds= pd.Series([1,2,3,4,5,6,7,8,9,5,3])
ds
print("Mean of the said Data Series: ")
ds.mean()


Mean of the said Data Series: 


4.818181818181818

In [20]:
print("Standard deviation of the said Data Series: ")
ds.std()

Standard deviation of the said Data Series: 


2.522624895547565

In [21]:
sr1= pd.Series([1,2,3,4,5])
sr2= pd.Series([2,4,6,8,10])
print("Items of sr1 not present in sr2:")
res = sr1[~sr1.isin(sr2)]
res

Items of sr1 not present in sr2:


0    1
2    3
4    5
dtype: int64

In [22]:
sr1= pd.Series([1,2,3,4,5])
sr2= pd.Series([2,4,6,8,10])
sr3= pd.Series(np.union1d(sr1,sr2))
sr4= pd.Series(np.intersect1d(sr1,sr2))
print("Items of a given series not present in another given series: ")
sr_new= sr3[~sr3.isin(sr4)]
sr_new

Items of a given series not present in another given series: 


0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

In [23]:
np.random.seed(100)
no = np.random.randint(1,21,10)
no


array([ 9,  4,  8, 16, 17, 11,  3,  3,  3, 15])

In [24]:
result = np.percentile(no,q=[0,25,50,75,100])
result

array([ 3.  ,  3.25,  8.5 , 14.  , 17.  ])

In [25]:
ser = np.random.randint(0,50,[25])
ser = pd.Series(ser)
ser.value_counts()

27    2
36    2
4     2
49    2
34    1
3     1
19    1
13    1
1     1
31    1
44    1
22    1
2     1
29    1
9     1
16    1
43    1
15    1
24    1
48    1
7     1
Name: count, dtype: int64

In [26]:
result = ser[~ser.isin(ser.value_counts().index[:1])] = 'Other'
result

C:\Users\dai.STUDENTSDC\AppData\Local\Temp\ipykernel_15220\1076278635.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Other' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  result = ser[~ser.isin(ser.value_counts().index[:1])] = 'Other'


'Other'

In [27]:
ser = np.random.randint(0,50,[25])
ser = pd.Series(ser)
result = ser[ser%5==0]
result

7     30
13    30
17    45
21     0
23    10
dtype: int32

In [28]:
ser = np.random.randint(0,50,[25])
ser = pd.Series(ser)
ser

0      8
1     13
2     42
3     30
4     17
5      4
6     40
7     27
8     27
9     19
10    14
11     0
12    13
13    12
14    42
15     3
16     6
17     3
18    20
19    15
20    10
21    23
22    47
23     3
24    41
dtype: int32

In [29]:
result = ser.take([15])
result

15    3
dtype: int32

In [30]:
s1 =  pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([1,3,5,7,10])
index = pd.Index(s1)
index

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [31]:
for i in s2:
    print(index.get_loc(i))

0
2
4
6
9


In [32]:
series = pd.Series(['php', 'python', 'java', 'c#'])
result = series.map(lambda x : x[0].upper() + x[1:-1] + x[-1].upper())
result

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

In [33]:
ser = pd.Series([1,3,5,8,10,11,15])
ser

0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64

In [34]:
ser = ser.to_list()
ser

[1, 3, 5, 8, 10, 11, 15]

In [35]:
for i in range(len(ser)-2):
    print(ser[i]-ser[i+1])

-2
-2
-3
-2
-1


In [36]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
date_series


0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [37]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
date_series

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [38]:
date_series = pd.to_datetime(date_series, format = 'mixed')

In [39]:
date_series

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [40]:
date_series.dt.day

0     1
1     2
2     7
3     6
4    12
5     6
dtype: int32

In [41]:
date_series.dt.month

0     1
1    10
2     3
3     5
4     4
5     4
dtype: int32

In [42]:
date_series.dt.year

0    2015
1    2016
2    2018
3    2014
4    2016
5    2019
dtype: int32

In [43]:
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
date_series
result = "11 " + date_series
result = pd.to_datetime(result)
result



0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

In [44]:
ser = pd.Series(['Red','Green', 'Orange', 'Pink', 'Yellow', 'White'])
filtered_words = ser[ser.str.contains(r'[aeiou].*[aeiou]', case=False)]
filtered_words


1     Green
2    Orange
4    Yellow
5     White
dtype: object

In [45]:
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Euclidean distance between two said series: ")
np.linalg.norm(x-y)

Euclidean distance between two said series: 


16.492422502470642

In [46]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Positions of the values surrounded by smaller values on both sides:")
temp = np.diff(np.sign(np.diff(nums)))
res = np.where(temp == -2)[0] + 1
print(res)

Positions of the values surrounded by smaller values on both sides:
[1 4 8]


In [48]:
str1 = 'abc def abcdef icd'
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
print(element_freq)
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ', current_freq))
print(result)

c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
Name: count, dtype: int64
abcidefiabcdefiicd


In [49]:
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]
print("\nAutocorrelations of the said series:")
print(autocorrelations[1:])


Autocorrelations of the said series:
[0.4, 0.04, -0.31, -0.51, -0.58, -0.06, 0.35, 0.38, 0.66, 0.83]


In [50]:
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2019:")
print(result)

All Sundays of 2019:
0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]


In [51]:
char_list = list('ABCDEFGHIJKLMNOP')
num = np.arange(8)
num_dict = dict(zip(char_list, num))
num_ser = pd.Series(num_dict)
df = num_ser.to_frame().reset_index()
print(df.head())

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4


In [58]:
series1 = pd.Series(range(10))
series2 = pd.Series(list('pqrstuvwxy'))
vertical_stack = pd.concat([series1, series2], axis=0)
print("Vertical Stack:")
print(vertical_stack)

# Stacking Horizontally
horizontal_stack = pd.concat([series1, series2], axis=1)
print("\nHorizontal Stack:")
print(horizontal_stack)

Vertical Stack:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Horizontal Stack:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [55]:
nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original Series:")
print(nums1)
print(nums2)
print("Check 2 series are equal or not?")
print(nums1 == nums2)

Original Series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
Check 2 series are equal or not?
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool


In [56]:
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print("Original Series:")
print(nums)
print("Index of the first occurrence of the smallest and largest value of the said series:")
print(nums.idxmin())
print(nums.idxmax())


Original Series:
0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64
Index of the first occurrence of the smallest and largest value of the said series:
9
4


In [57]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 
print("Original DataFrame:")
print(df_data)
print("\nOriginal Series:")
print(sr_data)
print("\nCheck for inequality of the said series & dataframe:")
print(df_data.ne(sr_data, axis = 0))


Original DataFrame:
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83

Original Series:
0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64

Check for inequality of the said series & dataframe:
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
