In [4]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [6]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/anaconda-install/Library/include
    lib directory: C:/anaconda-install/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x86_64
   

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [8]:
arr = np.array([1,2,3,4])
np.all(arr)

True

In [9]:
arr= np.array([0,2,3,0])
np.any(arr)

True

In [12]:
("Finite?",np.isfinite(1))

('Finite?', True)

In [16]:
arr = np.array([1, -2, np.inf, -np.inf, 0, 3.5])

In [17]:
np.isposinf(arr)

array([False, False,  True, False, False, False])

In [18]:
np.isneginf(arr)

array([False, False, False,  True, False, False])

In [20]:
arr = np.array([1, -2, np.nan, np.inf, 0, 3.5])
np.isnan(arr)

array([False, False,  True, False, False, False])

In [26]:
arr = np.array([1+1j, 1+5j, 3.2 ,4, 2j])
np.iscomplex(arr)

array([ True,  True, False, False,  True])

In [27]:
np.isreal(arr)

array([False, False,  True,  True, False])

In [28]:
np.isscalar(3.2)

True

In [29]:
np.isscalar([3.2])

False

In [32]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_a> arr_b

array([False, False, False])

In [33]:
arr_a < arr_b

array([ True,  True,  True])

In [34]:
np.greater_equal([1,2,3], [4,5,6])

array([False, False, False])

In [35]:
arr_a >= arr_b

array([False, False, False])

In [36]:
np.less_equal([1,2,3],[4,5,6])

array([ True,  True,  True])

In [37]:
arr_a <= arr_b

array([ True,  True,  True])

In [42]:
arr= np.array([1,7,13,105])
arr

array([  1,   7,  13, 105])

In [46]:
np.shape(arr)

(4,)

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
arr = np.zeros(10)

In [51]:
arr[:] = 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [52]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.random.randint(0,1)

0

In [55]:
np.random.randn(15)

array([-0.36753276,  0.33425436, -1.62937034, -0.60115976, -0.44643247,
        1.5307943 , -0.19954896, -0.28298201,  0.82549524, -0.75489618,
        0.19731829,  0.15636289,  0.92363872, -0.93443872, -0.51208547])

In [56]:
arr=np.arange(15,55)
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [58]:
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [60]:
arr = np.linspace(15,55,12)
arr.reshape(3,4)

array([[15.        , 18.63636364, 22.27272727, 25.90909091],
       [29.54545455, 33.18181818, 36.81818182, 40.45454545],
       [44.09090909, 47.72727273, 51.36363636, 55.        ]])

In [65]:
arr = np.arange(8,20).reshape((3,4))
arr

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
arr = np.random.randint(10,50,12).reshape((3,4))

In [67]:
arr

array([[22, 10, 46, 26],
       [26, 10, 33, 46],
       [23, 31, 26, 29]])

In [68]:
arr = np.linspace(5,50,10)

In [69]:
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [71]:
arr= np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [72]:
arr[(arr>=9)&(arr<=15)] *= -1
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [73]:
arr= np.random.randint(0,10,5)

In [74]:
arr

array([1, 8, 9, 2, 3])

In [77]:
arr_1 = np.random.randint(5)
arr_2 = np.arange(5)
arr_1*arr_2

array([0, 1, 2, 3, 4])

In [79]:
arr_1= np.array([4,5,6])
arr_2= np.array([5,9,7])
arr_1*arr_2

array([20, 45, 42])

In [80]:
arr= np.arange(10,22).reshape((3,4))
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [81]:
np.shape(arr)

(3, 4)

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [213]:
arr= np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [279]:
arr= np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [280]:
arr.size

100

In [281]:
arr = np.zeros(25).reshape(5,5)
arr[0][0]=1
arr[1][1]=2
arr[2][2]=3
arr[3][3]=4
arr[4][4]=5
arr



array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [282]:
arr = np.random.random((3,3,3))
arr

array([[[0.90511622, 0.41705151, 0.17345449],
        [0.0320087 , 0.92783115, 0.00809426],
        [0.39468203, 0.19316802, 0.29890091]],

       [[0.93237881, 0.73760769, 0.44599259],
        [0.80338135, 0.04969052, 0.15603656],
        [0.72225058, 0.49198334, 0.94419839]],

       [[0.24221636, 0.26339558, 0.99019964],
        [0.16022599, 0.14347302, 0.19120145],
        [0.41722695, 0.10740919, 0.17204837]]])

In [283]:
a = np.arange(5)
b = np.arange(5)
print(a)
print(b)
np.inner(a,b)

[0 1 2 3 4]
[0 1 2 3 4]


30

In [284]:
arr = np.random.randint(0,25,25)
arr = arr.reshape(5,5)
arr

array([[10,  2, 17,  1, 21],
       [12, 13,  0,  6, 11],
       [ 5, 24, 24,  8,  3],
       [18, 15, 17,  3,  0],
       [18,  8, 23,  1, 14]])

In [285]:
arr1 = np.sort(arr,axis=0)
arr1

array([[ 5,  2,  0,  1,  0],
       [10,  8, 17,  1,  3],
       [12, 13, 17,  3, 11],
       [18, 15, 23,  6, 14],
       [18, 24, 24,  8, 21]])

In [286]:
arr2 = np.sort(arr1,axis = 1)
arr2

array([[ 0,  0,  1,  2,  5],
       [ 1,  3,  8, 10, 17],
       [ 3, 11, 12, 13, 17],
       [ 6, 14, 15, 18, 23],
       [ 8, 18, 21, 24, 24]])

In [287]:
arr = np.array([2,4,6,1,2,98])
arr.sort()
arr

array([ 1,  2,  2,  4,  6, 98])

In [288]:
arr[arr>5]

array([ 6, 98])

In [289]:

arr[arr>3] = 0
arr

array([1, 2, 2, 0, 0, 0])

In [290]:
arr.dtype

dtype('int32')

In [291]:
arr.ndim

1

In [292]:
arr.size

6

In [293]:
arr.shape

(6,)

In [294]:
arr= np.arange(2,11).reshape(3,3)
arr


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [295]:
np.empty_like(arr)

array([[    0,     1,     0],
       [  524,  1540,     0],
       [  768, 32767,     0]])

In [296]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [297]:
arr= np.random.random((3,5,4))
arr

array([[[0.24201241, 0.88717187, 0.94372199, 0.10143079],
        [0.08032823, 0.49109477, 0.10407915, 0.50228971],
        [0.39008991, 0.30686731, 0.44806078, 0.82229065],
        [0.58703498, 0.301348  , 0.09019483, 0.31304976],
        [0.98126164, 0.40017112, 0.06694841, 0.70338084]],

       [[0.05223312, 0.17512852, 0.9981172 , 0.02123021],
        [0.8252574 , 0.35983108, 0.61750671, 0.32342511],
        [0.05567909, 0.67254671, 0.87151849, 0.61665464],
        [0.93919372, 0.07363179, 0.43487081, 0.31494572],
        [0.34258002, 0.2536401 , 0.17542476, 0.7067078 ]],

       [[0.25972233, 0.58871156, 0.73380661, 0.30561563],
        [0.09633534, 0.38476402, 0.41773216, 0.21943888],
        [0.18630266, 0.11196702, 0.34628414, 0.57038953],
        [0.70539886, 0.60985309, 0.87614671, 0.96892498],
        [0.11959734, 0.28869303, 0.78982916, 0.49775706]]])